FROM python:3.13-slim
WORKDIR /app
COPY pyproject.toml .
RUN pip install -e ".[front]"
COPY front/ ./front/
COPY api/ ./api/
CMD ["streamlit", "run", "front/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
