services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - /data/waterflow/models:/app/models
    networks:
      - coolify

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - /data/waterflow/models:/app/models
    environment:
      - WATERFLOW_API=http://api:8000/api/predict
    depends_on:
      - api
    networks:
      - coolify

networks:
  coolify:
    external: true